apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabriella-db
  namespace: grupp5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gabriella-db
  template:
    metadata:
      labels:
        app: gabriella-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "gabriella_user"
        - name: POSTGRES_PASSWORD
          value: "gabriella_password"
        - name: POSTGRES_DB
          value: "guestbook_db"
