apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabriella-backend
  namespace: grupp5
  labels:
    app: gabriella-backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: gabriella-backend
  template:
    metadata:
      labels:
        app: gabriella-backend
    spec:
      containers:
      - name: backend
        image: quay.io/gabohr/guestbook-backend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: DB_HOST
          value: "gabriella-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gabriella-db-secret
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gabriella-db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gabriella-db-secret
              key: password
