apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabriella-backend
  namespace: grupp5
  labels:
    app: gabriella-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gabriella-backend
  template:
    metadata:
      labels:
        app: gabriella-backend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: backend
        image: quay.io/jonasbjork/guestbook-backend:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "gabriella-db"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gabriella-db-secret
              key: database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gabriella-db-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: gabriella-db-secret
              key: password
