apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabriella-frontend
  namespace: grupp5
  labels:
    app: gabriella-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gabriella-frontend
  template:
    metadata:
      labels:
        app: gabriella-frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/jonasbjork/guestbook-frontend:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: BACKEND_HOST
          value: "gabriella-backend"
