apiVersion: apps/v1
kind: Deployment
metadata:
  name: gabriella-frontend
  namespace: grupp5
  labels:
    app: gabriella-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gabriella-frontend
  template:
    metadata:
      labels:
        app: gabriella-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        image: quay.io/jonasbjork/guestbook-frontend:latest
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_HOST
          value: "gabriella-backend"
